### ISSUE TITLE
有优势吗？UltraPixel能生成6K图片

### ISSUE THREAD

**Issue by O-O1024** [haoningwu3639/MegaFusion#1]

**Comment by haoningwu3639** [comment]
To the best of our knowledge, UltraPixel requires further fine-tuning diffusion models, whereas our proposed MegaFusion is a tuning-free strategy that can effectively extend the high-resolution generation capabilities of existing diffusion models. Although we have not generated 6K resolution images, theoretically, with sufficient optimization and computational resources, MegaFusion can also synthesize images at even higher resolutions.
