### ISSUE TITLE
Release Code

### ISSUE THREAD

**Issue by Roveer** [haoningwu3639/MegaFusion#2]
Do you have any plans to release code?

**Comment by haoningwu3639** [comment]
Yeah, recently, we have further added some quantitative and qualitative experiments. We have also updated a new version of our paper. 
We appreciate your understanding as we are taking the time to organize the code and plan to release it as soon as possible. If you are interested, please stay tuned!

**Comment by Njasa2k** [comment]
> Yeah, recently, we have further added some quantitative and qualitative experiments. We have also updated a new version of our paper. We appreciate your understanding as we are taking the time to organize the code and plan to release it as soon as possible. If you are interested, please stay tuned!

any update?

**Comment by vladmandic** [comment]
since its been over 3 months, its pretty safe to assume this project to be dead-on-arrival?

**Comment by haoningwu3639** [comment]
Sorry, everyone! My collaborators and I have been busy with other paper submissions recently, so we have been delayed for so long! 
Fortunately, we finally have time to organize and open-source the code of MegaFusion! We will gradually open-source the rest of the code very soon, please stay tuned. 
Considering the large amount of code in the whole project, please be patient. Thank you everyone!
